# Generated by Django 2.2.6 on 2019-11-27 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duration', models.TimeField()),
                ('winner', models.CharField(choices=[('W', 'White'), ('B', 'Black'), ('D', 'Draw')], default='D', max_length=2)),
                ('black_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_as_black', to=settings.AUTH_USER_MODEL)),
                ('white_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_as_white', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
